
import { PinataSDK } from "pinata"

const jwt="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiIwOTViMTg0YS03ZjgxLTRjODItODRlYS1jYzA1YmJjNmE3NTMiLCJlbWFpbCI6InNhbHVua2VvbTQ3NEBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGluX3BvbGljeSI6eyJyZWdpb25zIjpbeyJkZXNpcmVkUmVwbGljYXRpb25Db3VudCI6MSwiaWQiOiJGUkExIn0seyJkZXNpcmVkUmVwbGljYXRpb25Db3VudCI6MSwiaWQiOiJOWUMxIn1dLCJ2ZXJzaW9uIjoxfSwibWZhX2VuYWJsZWQiOmZhbHNlLCJzdGF0dXMiOiJBQ1RJVkUifSwiYXV0aGVudGljYXRpb25UeXBlIjoic2NvcGVkS2V5Iiwic2NvcGVkS2V5S2V5IjoiMDFiOGQyYmJkMzNlZmJkYzk4YWQiLCJzY29wZWRLZXlTZWNyZXQiOiJhNWNmM2ZkYzJjN2IwNzViNjhmNTNhZmFkOGQ1MzRiZWI5YmM3ZTBmNGUwNTYxOTgzYTZhZWM1YWMzY2I3Mjc4IiwiZXhwIjoxNzgzOTI4NTUzfQ.Ato8nlFI9VGIu4CYIw0mXZ2-Oaj3wVw6O6LNHXOUni0"
const gateway_url="https://harlequin-managing-cattle-394.mypinata.cloud-"
export const pinata = new PinataSDK({
  pinataJwt: `${jwt}`,
  pinataGateway: `${gateway_url}`
})